### ISSUE TITLE
Ideal experimental feature switch not working

### ISSUE THREAD

**Issue by jurjendevries** [CoinCollect/coincollect-app#1]
**Version:** 1.6.1 (google play) / 1.6.11 (app) - Android

**Steps to reproduce the problem:**

1. Enter pin
2. Click settings (gear icon)
3. Enable 'Experimental features'
4. Disable Ideal
5. go back to overview screen
6. click a coin with ideal facility such as Ethereum

Buy button is visible

**expected behavior:**
No visibility of buy button because feature is disabled.

**Comment by nomoca** [comment]
Thank you for this feedback.

The `iDeal test payments` toggle has been removed. It was unclear what this toggle would do.

If you now enable "Experimental features", the Buy button will be visible in BTC/ETH/LTC. If you disable "Experimental features", it will hide the Buy button.

In the future the Buy button will be visible in the app by default. Other, newer features will be shown by having the "Experimental features" enabled. It's kind of a Permanent Beta option.

I will close this issue as the issue has been resolved by improving the UI.
