### ISSUE TITLE
version difference between Android & App

### ISSUE THREAD

**Issue by jurjendevries** [CoinCollect/coincollect-app#2]
**Version:** 1.6.1 (google play) / 1.6.11 (app) - Android

**Steps to reproduce the problem:**

1. In Android go to 'App info' screen of Coincollect or go to Google Play Coincollect screen
2. See displayed version 1.6.1
3. In CoinCollect enter pin
4. Go to settings (gear icon)
5. See displayed version is 1.6.11

**expected behavior:**
Same version number

**Comment by nomoca** [comment]
Thanks for the feedback.

Right now this works as follow:
- If a new app version is added to the Android app store, this app uses a certain version number. 1.6.1 in your case.
- After adding a new version of the app to the app store, the app can still get updates, using hot push updates. If this happens, the version number in the Config menu goes up as well. From that moment Play Store version and app version are different. The next time a new Google Play Store app is uploaded to the Google Play Store, both version indicators are equal again.

Tip: If you give feedback, please give the version number that's in the Config menu in the app. This one shows what's the most recent version of the app.

**Comment by jurjendevries** [comment]
Thanks. Clear for me now. But I think not for other users who don't see this thread and may report an issue just by the store version or so. What about making a totally different push version number so that it is easy to distinguish?

**Comment by nomoca** [comment]
![image](https://user-images.githubusercontent.com/59296461/71541620-2b652380-295c-11ea-9ad2-f1620931f3f5.png)

Good point.

Maybe it should be:
- App version: `1.6.1`
- `(v1)` -> `(v2)` -> etc

Every week or so there'll be a new App version and the version counter starts with v1 again.

**Comment by jurjendevries** [comment]
Good one. This way devs can distinguish if the issue reporter only gave the app version or also added the hot push version number.

**Comment by bartwr** [comment]
@jurjendevries From now you'll see the Web version number next to the App version number in the Config menu:

![image](https://user-images.githubusercontent.com/899234/71701149-18bd7500-2dc8-11ea-90ae-448a3a95786c.png)

Thanks again!
