### ISSUE TITLE
Ideal text label not visible in settings

### ISSUE THREAD

**Issue by jurjendevries** [CoinCollect/coincollect-app#3]
**Version:** 1.6.1 (google play) / 1.6.11 (app) - Android

**Steps to reproduce the problem:**

1. Enter pin
2. Click settings (gear icon)
3. Enable 'Experimental features'
4. You'll get an extra switch without text in the front (see attached screenshot)

Nb. this worked well yesterday for me. I don't know why I don't see it now. I tried to restart the app, but still the same issue.

**expected behavior:**
Visible ideal text label

![Screenshot_20191224-122803](https://user-images.githubusercontent.com/355488/71394308-e4211f00-264b-11ea-8f50-1d5a0afdce66.png)

**Comment by nomoca** [comment]
This issue has been solved.

The "Test iDeal" option was removed last week. A new option for testing the Christmas campaign was added. This option had no readable text, it was just a toggle.

Right now only the "Experimental features" toggle is in the Config menu. It's much clearer this way.

Again, thanks for the feedback!
