### ISSUE TITLE
EUR field is using USD value

### ISSUE THREAD

**Issue by jurjendevries** [CoinCollect/coincollect-app#6]
Version: 1.8.0 (google play) / 1.8.0 (app) - Android

Steps to reproduce the problem:

Enter pin
Click a coin (in my case SAI)
Click send
Click send all

The EUR field is filled with USD calculated value instead of EUR.

**Comment by bartwr** [comment]
Thanks for this bug report! We will have a look at this asap.

**Comment by nomoca** [comment]
This should be fixed now.

![image](https://user-images.githubusercontent.com/899234/72645304-a1651500-3973-11ea-8a8a-9525593c3135.png)

**Comment by jurjendevries** [comment]
Yes, tested and works well.
