### ISSUE TITLE
USD value shows EUR confirmation screen

### ISSUE THREAD

**Issue by jurjendevries** [CoinCollect/coincollect-app#7]
Version: 1.8.0 (google play) / 1.8.0 (app) - Android

Steps to reproduce the problem:

Enter pin
Click to settings
Choose currency (in my case USD)
Click a coin (in my case SAI)
Click send
Enter a valid address
Click send all
Click send

There is a yellow confirmation dialog "Do you really want to send € xx,xx worth of ETH to ... ? You'll spend € xx,xx including fees."

I expect that the € currency sign is a $ currency sign here. The amount of xx,xx is correct in USD, so no worries about that.

**Comment by nomoca** [comment]
This should be fixed now.

![image](https://user-images.githubusercontent.com/899234/72645341-b0e45e00-3973-11ea-82ad-0386971d2451.png)

**Comment by jurjendevries** [comment]
Tested and works well.
