### ISSUE TITLE
Sanitize seed input when recovering wallet

### ISSUE THREAD

**Issue by kitblake** [CoinCollect/coincollect-app#8]
A user on Discord reported that when he input his seed it had line breaks and the recover failed. Lots of users probably have line breaks, because:

- When the seed words are presented, they're in sets of four. Many users type the words into a password manager.
- If you've done this before, you know you're going to be tested, and the app will ask for, e.g. word number 17. If you have breaks, it's much easier to figure out which is the 17th word.
- If a user has the seed words stored with breaks, the phrase will prob get copied with the breaks. 

So when doing a recover, the app should sanitize the seed input and replace line breaks with spaces. This will save users a lot of grief, and preempt support requests too.

**Comment by bartwr** [comment]
Thank you for helping CoinCollect improve, @kitblake ! 

This should be fixed from tonight. CoinCollect will replace the newlines into spaces automatically.

![image](https://user-images.githubusercontent.com/899234/73973188-6aef3a00-4922-11ea-9ce7-f350b07d083a.png)

**Comment by kitblake** [comment]
Cool 👍  That's a helpful preventative feature.
